version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.8.0  # Use a Node.js image
    steps:
      - checkout  # Pull your repo code
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Start the App in the Background
          command: npm start & sleep 10  # Run the app and wait for it to start

workflows:
  version: 2
  test-app:
    jobs:
      - test