export default {
    137: {
        "coverage_vfbl": "VFBL Coverage Requested",
        "coverage_wc": "WC Coverage Requested",
        "effective_date": "Requested Effective Date",
        "entity_name": "Name of Entity",
        "mailing_address": "Mailing Address",
        "fein": "FEIN #",
        "county": "County",
        "primary_contact": "Primary Contact Name",
        "contact_title": "Title",
        "telephone": "Telephone #",
        "fax": "Fax #",
        "website": "Website",
        "email": "E‑mail Address",
        "broker_name": "Broker Name",
        "broker_address": "Broker Address",

        "officer_name_1": "Officer 1 Name",
        "officer_title_1": "Officer 1 Title",
        "officer_phone_1": "Officer 1 Phone",
        "officer_name_2": "Officer 2 Name",
        "officer_title_2": "Officer 2 Title",
        "officer_phone_2": "Officer 2 Phone",
        "officer_name_3": "Officer 3 Name",
        "officer_title_3": "Officer 3 Title",
        "officer_phone_3": "Officer 3 Phone",
        "officer_name_4": "Officer 4 Name",
        "officer_title_4": "Officer 4 Title",
        "officer_phone_4": "Officer 4 Phone",
        "officer_name_5": "Officer 5 Name",
        "officer_title_5": "Officer 5 Title",
        "officer_phone_5": "Officer 5 Phone",

        "main_location": "Main Location",
        "other_locations": "Other Locations",
        "other_location_2": "Other Location 2",
        "other_location_3": "Other Location 3",
        "other_location_4": "Other Location 4",

        "vfbl_carrier": "VFBL Carrier",
        "vfbl_policy": "VFBL Policy Number",
        "vfbl_period": "VFBL Policy Period",
        "vfbl_premium": "VFBL Annual Premium",
        "wc_carrier": "WC Carrier",
        "wc_policy": "WC Policy Number",
        "wc_period": "WC Policy Period",
        "wc_premium": "WC Annual Premium",

        "applicant_initial": "Applicant's Initial",

        "population": "Estimated Population",
        "population_desc": "Population Description",
        "square_mileage": "Square Mileage Served",
        "area_desc": "Area Description",

        "contract_outside": "Has Contract Outside Home Area",
        "assist_other_fd": "Assist Other Fire Dept",
        "assistedDept1": "Assisted Dept 1",
        "assistedPop1": "Assisted Pop 1",
        "assistedMiles1": "Assisted Miles 1",
        "assistedDesc1": "Assisted Desc 1",
        "assistedDept2": "Assisted Dept 2",
        "assistedPop2": "Assisted Pop 2",
        "assistedMiles2": "Assisted Miles 2",
        "assistedDesc2": "Assisted Desc 2",
        "assistedDept3": "Assisted Dept 3",
        "assistedPop3": "Assisted Pop 3",
        "assistedMiles3": "Assisted Miles 3",
        "assistedDesc3": "Assisted Desc 3",
        "assistedDept4": "Assisted Dept 4",
        "assistedPop4": "Assisted Pop 4",
        "assistedMiles4": "Assisted Miles 4",
        "assistedDesc4": "Assisted Desc 4",

        "mutual_aid": "Provides Mutual Aid",
        "mutual_aid_list": "Mutual Aid Fire Departments",

        "ambulance": "Provides Ambulance Transport",
        "ambulance_count": "Ambulance Count",
        "emt_count": "EMT Count",
        "fire_calls": "Annual Fire Calls",
        "ems_calls": "Annual EMS Calls",

        "juniors": "Has Juniors Program",

        "racing_motorized": "Motorized Racing Team",
        "racing_motorized_count": "Motorized Races Per Year",
        "racing_old": "Old-Fashioned Racing Team",
        "racing_old_count": "Old-Fashioned Races Per Year",
        "racing_none": "No Racing Team",
        "members_outside_team": "Members Race Outside District",

        "safety_officer": "Has NYS Certified Safety Officer",
        "safety_officer_count": "Certified Safety Officer Count",
        "safety_committee": "Has Safety Committee",
        "safety_procedures": "Has Written Safety Procedures",

        "page2_initial": "Applicant's Initial (Page 2)",

        "veh_count": "Active Emergency Vehicles",
        "vol_ff_count": "Active Volunteer Firefighters",
        "class_a": "Volunteer FF Class A",
        "class_b": "Volunteer FF Class B",
        "class_c": "Volunteer FF Class C",
        "class_d": "Volunteer FF Class D",

        "emp_ff_num": "Paid Firefighters Count",
        "emp_ff_pay": "Paid Firefighters Payroll",
        "emp_emt_num": "Paid EMTs Count",
        "emp_emt_pay": "Paid EMTs Payroll",
        "emp_disp_num": "Dispatchers Count",
        "emp_disp_pay": "Dispatchers Payroll",
        "emp_clerical_num": "Clerical Employees Count",
        "emp_clerical_pay": "Clerical Employees Payroll",
        "emp_jan_num": "Janitorial Employees Count",
        "emp_jan_pay": "Janitorial Employees Payroll",
        "emp_mech_num": "Mechanics Count",
        "emp_mech_pay": "Mechanics Payroll",
        "emp_insp_num": "Building Inspectors Count",
        "emp_insp_pay": "Building Inspectors Payroll",
        "emp_other1_class": "Other Classification 1",
        "emp_other1_num": "Other Classification 1 Count",
        "emp_other1_pay": "Other Classification 1 Payroll",
        "emp_other2_class": "Other Classification 2",
        "emp_other2_num": "Other Classification 2 Count",
        "emp_other2_pay": "Other Classification 2 Payroll",
        "emp_other3_class": "Other Classification 3",
        "emp_other3_num": "Other Classification 3 Count",
        "emp_other3_pay": "Other Classification 3 Payroll",

        "fire_commissioners": "Number of Fire Commissioners",

        "signature": "Authorized Officer's Signature",
        "print_name": "Print Name",
        "title": "Officer Title",
        "date": "Date Signed"
    }

}